# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"get_files": "00_core.ipynb",
         "UnpicklerModule": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://muellerzr.github.io/unpickler/"

git_url = "https://github.com/muellerzr/unpickler/tree/master/"

def custom_doc_links(name): return None
